const double kDouble5 = 5.0;
const double kDouble10 = 10.0;
const double kDouble20 = 20.0;
const double kDouble40 = 40.0;

const String selfCareDescription1 =
    "Self-care is an essential practice that encompasses nurturing one's physical, emotional, and mental well-being. It is an act of self-compassion and self-respect. Engaging in self-care activities allows individuals to recharge and replenish their inner resources, enabling them to better navigate the demands of daily life. It involves a range of activities, from taking time for relaxation and leisure to maintaining a healthy lifestyle through exercise and nutrition. Self-care also involves setting boundaries, saying no when necessary, and seeking support when facing challenges. Ultimately, self-care is a powerful tool for achieving balance, resilience, and a sense of inner peace, enabling individuals to lead healthier, happier lives.";

const String selfCareDescription2 =
    "There are numerous activities and practices you can incorporate into your routine to improve self-care. These activities cater to various aspects of your well-being, including physical, emotional, and mental health. Here are some examples:";

const String rocketDescription3 =
    "(01). Exercise: Regular physical activity not only benefits your body but also releases endorphins, which boost your mood and reduce stress.\n(02). Healthy Eating: Nourishing your body with a balanced diet rich in fruits, vegetables, and whole grains can have a profound impact on your energy levels and overall health.\n(03). Sleep: Prioritize getting enough sleep, as it is essential for physical and mental recovery. Aim for 7-9 hours of quality sleep each night.\n(04). Mindfulness and Meditation: Practicing mindfulness and meditation can help you manage stress, improve focus, and cultivate a sense of inner calm.\n(05). Journaling: Writing down your thoughts and feelings can be a therapeutic way to process emotions and gain clarity about your life.\n(06). Hobbies and Leisure Activities: Engaging in activities you enjoy, whether it's painting, gardening, reading, or playing a musical instrument, can provide relaxation and fulfillment.\n(07). Social Connections: Spend time with friends and loved ones. Building and nurturing social connections is vital for emotional well-being.\n(08). Setting Boundaries: Learn to say no when necessary and establish healthy boundaries to protect your time and energy.\n(09). Professional Support: Don't hesitate to seek help from a therapist, counselor, or coach when dealing with challenging emotional or mental issues.\n(10). Self-Compassion: Practice self-compassion by treating yourself with kindness, understanding, and forgiveness, just as you would a friend.\n(11). Digital Detox: Take breaks from screens and technology to reduce stress and improve sleep quality.\n(12). Regular Check-ups: Don't neglect your physical health; schedule regular check-ups with healthcare professionals to address any potential issues early.\n(13). Time Management: Efficiently manage your time to reduce stress and make space for self-care activities.\n(14). Gratitude Practice: Cultivate gratitude by acknowledging and appreciating the positive aspects of your life.\n(15). Nature and Outdoors: Spend time in nature to refresh your mind and boost your mood.\n(16). Self-Reflection: Set aside time for introspection and self-reflection to gain a deeper understanding of yourself and your needs.\n(17). Creative Expression: Express yourself creatively through art, writing, or other forms of self-expression.\n(18). Learning and Personal Growth: Engage in continuous learning and personal development to foster a sense of purpose and fulfillment.\n";
