// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAblrt-9DyPoaGQILO2bGS2CxyCPgkwPkI',
    appId: '1:277496527429:web:50c2ef8c6db41597e8c12c',
    messagingSenderId: '277496527429',
    projectId: 'bloomi-e01b6',
    authDomain: 'bloomi-e01b6.firebaseapp.com',
    storageBucket: 'bloomi-e01b6.appspot.com',
    measurementId: 'G-VGWZ8FR3E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PNp1acvj4GnQ8OUZDHWJ5aNxcQiiUAQ',
    appId: '1:277496527429:android:03da675314a66cc4e8c12c',
    messagingSenderId: '277496527429',
    projectId: 'bloomi-e01b6',
    storageBucket: 'bloomi-e01b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjzcc5bE5YvWprvrhL6xYHxLJe0GOkks',
    appId: '1:277496527429:ios:65b66539d2d17d7fe8c12c',
    messagingSenderId: '277496527429',
    projectId: 'bloomi-e01b6',
    storageBucket: 'bloomi-e01b6.appspot.com',
    iosBundleId: 'com.example.bloomiWeb',
  );
}
